// <auto-generated />
using EmployeeDetails.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EmployeeDetails.Migrations
{
    [DbContext(typeof(EmployeeDbContext))]
    [Migration("20240614111931_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EmployeeDetails.Model.EmployeEntities", b =>
                {
                    b.Property<int>("EmployeEntitiesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EmployeEntitiesId"));

                    b.Property<string>("Deparement")
                        .HasColumnType("text");

                    b.Property<string>("EmpName")
                        .HasColumnType("text");

                    b.Property<double>("Packege")
                        .HasColumnType("double precision");

                    b.Property<double>("Salaree")
                        .HasColumnType("double precision");

                    b.HasKey("EmployeEntitiesId");

                    b.ToTable("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
